// import './../static/2-3'
// import './../static/2-4'
// import './../static/2-5'
// import './../static/2-6'
// import './../static/2-7'
// import './../static/2-8'
// import './../static/2-9'
// import './../static/2-10'
// import './../static/2-11'
// import './../static/2-12'
import './../static/2-13'
